spring.datasource.url=jdbc:mysql://db:3306/webservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=webuser
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update        # albo create-drop / validate – zależnie od potrzeb
spring.jpa.show-sql=true
